# Generated by Django 5.2.4 on 2025-07-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, unique=True)),
                ('twitter', models.CharField(max_length=255)),
                ('retweet', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('referral_code', models.CharField(max_length=10, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=10, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('pin', models.PositiveIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
